from PyQt5 import QtCore, QtGui, QtWidgets
class AboutMeDialog(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        self.Dialog.setObjectName("AboutMe")
        self.Dialog.resize(640, 517)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Dialog.setFont(font)
        self.aboutme_banner = QtWidgets.QLabel(self.Dialog)
        self.aboutme_banner.setGeometry(QtCore.QRect(170, 20, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Nokia Standard Light")
        font.setPointSize(30)
        self.aboutme_banner.setFont(font)
        self.aboutme_banner.setObjectName("aboutme_banner")
        self.line = QtWidgets.QFrame(self.Dialog)
        self.line.setGeometry(QtCore.QRect(20, 110, 601, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 160, 201, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(77, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 160, 271, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 84, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.aboutme_close = QtWidgets.QPushButton(self.Dialog)
        self.aboutme_close.setGeometry(QtCore.QRect(210, 450, 161, 28))
        self.aboutme_close.setStyleSheet("color:Red")
        self.aboutme_close.setObjectName("aboutme_close")
        self.aboutme_explain = QtWidgets.QLabel(Dialog)
        self.aboutme_explain.setGeometry(QtCore.QRect(30, 70, 611, 61))
        self.aboutme_explain.setObjectName("aboutme_explain")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(70, 120, 20, 311))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(570, 120, 20, 311))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(80, 420, 501, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(290, 120, 16, 311))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(self.Dialog)
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)
    def CloseAboutMe(self):
    	self.Dialog.close()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About The Programmer "))
        self.aboutme_banner.setText(_translate("Dialog", "Vocabuilder"))
        self.label_3.setText(_translate("Dialog", "Name : "))
        self.label_4.setText(_translate("Dialog", "Email Address :"))
        self.label_5.setText(_translate("Dialog", "Facebook : "))
        self.label_6.setText(_translate("Dialog", "Github : "))
        self.label_7.setText(_translate("Dialog", "Instagram : "))
        self.label_9.setText(_translate("Dialog", "Tanmay Upadhyay"))
        self.label_11.setText(_translate("Dialog", "kevinthemetnik@gmail.com"))
        self.label_10.setText(_translate("Dialog", "/tanmayupadhyay91"))
        self.label_12.setText(_translate("Dialog", "tanmay606"))
        self.label_8.setText(_translate("Dialog", "tanmay.606"))
        self.aboutme_close.setText(_translate("Dialog", "Close"))
        self.aboutme_explain.setText(_translate("Dialog", "- If you have any suggestions, criticism, or want to stay connected with me here are my media accounts."))
        self.aboutme_close.clicked.connect(self.CloseAboutMe)

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    AboutMeUi = AboutMeDialog()
    AboutMeUi.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())
"""