try:
	from PyQt5 import QtCore, QtGui, QtWidgets
	from NewCatagory import Ui_CreateNewCatagory
	from opencata import OpenCata_
	from aboutme import AboutMeDialog
except ImportError:
	print("Please Make Sure You Have All The Modules To Use This Program.")
	print("\n")
	input()

class Ui_MainProgram(object):
    def OpenCatagories(self):
        self.OpenCata = QtWidgets.QDialog()
        self.OpenCataUI = OpenCata_()
        self.OpenCataUI.setupUi(self.OpenCata)
        self.OpenCata.show()
    def CreateNewCatagory(self):
        self.CreateNewCatagory = QtWidgets.QDialog()
        self.CreateNewCatagoryUI = Ui_CreateNewCatagory()
        Ui_CreateNewCatagory.__init__(self)
        self.CreateNewCatagoryUI.setupUi(self.CreateNewCatagory)
        self.CreateNewCatagory.show()
    def ShowAboutMe(self):
        self.AboutDialog = QtWidgets.QDialog()
        self.AboutMeUi = AboutMeDialog()
        self.AboutMeUi.setupUi(self.AboutDialog)
        self.AboutDialog.show()

    def setupUi(self, MainProgram):
        MainProgram.setObjectName("MainProgram")
        MainProgram.resize(621, 439)
        self.mainprogram_title = QtWidgets.QLabel(MainProgram)
        self.mainprogram_title.setGeometry(QtCore.QRect(160, -10, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Nokia Standard Light")
        font.setPointSize(30)
        self.mainprogram_title.setFont(font)
        self.mainprogram_title.setObjectName("mainprogram_title")
        self.punchline = QtWidgets.QLabel(MainProgram)
        self.punchline.setGeometry(QtCore.QRect(140, 130, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.punchline.setFont(font)
        self.punchline.setObjectName("punchline")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainProgram)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 200, 381, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainprogram_createvault = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mainprogram_createvault.setFont(font)
        self.mainprogram_createvault.setMouseTracking(False)
        self.mainprogram_createvault.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mainprogram_createvault.setAcceptDrops(False)
        self.mainprogram_createvault.setWhatsThis("")
        self.mainprogram_createvault.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainprogram_createvault.setAutoFillBackground(False)
        self.mainprogram_createvault.setStyleSheet("color:green")
        self.mainprogram_createvault.setObjectName("mainprogram_createvault")
        self.verticalLayout.addWidget(self.mainprogram_createvault)
        self.mainprogram_openvault = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mainprogram_openvault.setStyleSheet("color:green")
        self.mainprogram_openvault.setObjectName("mainprogram_openvault")
        self.verticalLayout.addWidget(self.mainprogram_openvault)
        self.mainprogram_close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mainprogram_close.setStyleSheet("color:red")
        self.mainprogram_close.setObjectName("mainprogram_close")
        self.verticalLayout.addWidget(self.mainprogram_close)
        self.mainprogram_commandLinkButton = QtWidgets.QCommandLinkButton(MainProgram)
        self.mainprogram_commandLinkButton.setGeometry(QtCore.QRect(160, 70, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(6)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.mainprogram_commandLinkButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("sad")
        self.mainprogram_commandLinkButton.setIcon(icon)
        self.mainprogram_commandLinkButton.setObjectName("mainprogram_commandLinkButton")
        self.line = QtWidgets.QFrame(MainProgram)
        self.line.setGeometry(QtCore.QRect(0, 110, 621, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(MainProgram)
        QtCore.QMetaObject.connectSlotsByName(MainProgram)

    def retranslateUi(self, MainProgram):
        _translate = QtCore.QCoreApplication.translate
        MainProgram.setWindowTitle(_translate("MainProgram", "Vocabuilder (Your Personal Vocabulary Retention Solution)"))
        self.mainprogram_title.setText(_translate("MainProgram", "Vocabuilder "))
        self.punchline.setText(_translate("MainProgram", "- Now Remember Every Word You\'ve Learned."))
        self.mainprogram_createvault.setText(_translate("MainProgram", "Create New Catagory"))
        self.mainprogram_openvault.setText(_translate("MainProgram", "Manage Categories"))
        self.mainprogram_close.setText(_translate("MainProgram", "Close"))
        self.mainprogram_commandLinkButton.setText(_translate("MainProgram", "ABOUT PROGRAMMER"))
        self.mainprogram_commandLinkButton.clicked.connect(self.ShowAboutMe)
        self.mainprogram_openvault.clicked.connect(self.OpenCatagories)
        self.mainprogram_createvault.clicked.connect(self.CreateNewCatagory)
        self.mainprogram_close.clicked.connect(exit)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainProgram = QtWidgets.QWidget()
    MainProgramUI = Ui_MainProgram()
    MainProgramUI.setupUi(MainProgram)
    MainProgram.show()
    sys.exit(app.exec_())
